"2026-01":
  Housing: 2000
  Food: 600
  Transportation: 400
  Giving: 500
  Lifestyle: 300
  Insurance: 260
  Personal: 200

"2026-02":
  Housing: 2000
  Food: 400
  Transportation: 500
  Giving: 500
  Lifestyle: 250
  Insurance: 260
  Personal: 200