# ======================
# INCOME
# ======================
maria_paychecks:
  - deposit ach
  - paycheck

rent_from_lizzy:
  - venmo

jose_paychecks:
  - deposit by check 

gift_money:
  - zelle
  - miguel

# =======================
# GIVING
# ======================
church:
  - saint edward
  - diocesen
  - church

charity:
  - lifeline child
  - st mary's bookstore
  - st marys bookstore

# ======================
# HOUSING
# ======================
rent:
  - bh life rent

utilities:
  - bh life rent

pet_rent:
  - pet rent

# ======================
# TRANSPORTATION
# ======================
gas:
  - auto care
  - gas
  - shell
  - exxon
  - chevron

other_car_fees:
  - auto
  - car

airfare:
  - united
  - united airlines
  - delta
  - spirit

# ======================
# FOOD
# ======================
groceries:
  - kroger
  - costco
  - publix
  - shoprite
  - wal-mart
  - walmart

eating_out_delivery:
  - popeyes
  - chipotle
  - moe's
  - chopt
  - diner
  - pizza
  - thai
  - no ches
  - grill
  - doordash
  - nochesdecolombia

coffee:
  - starbucks
  - dunkin
  - caliber coffee
  - the well coffeehouse
  - the well
  - panera

# ======================
# PERSONAL / LIFESTYLE
# ======================
personal:
  - mckay used books

health_hygiene:
  - walgreens
  - cvs

pet:
  - petco
  - petsmart
  - vetsource

personal_development:
  - amazon books
  - audible
  - wgu
  - boot.dev
  - comptia
  - tryhackme
  - udemy
  - hackthebox
  - violin shop
  - myperfectresume

entertainment:
  - amc theatres
  - amc
  - regal cinemas 

subscriptions:
  - netflix
  - spotify
  - hulu
  - disney+
  - crunchydrive
  - amazon prime
  - notion
  - prime video

business_expenses:
  - cloudflare
  - tnsos business

# ======================
# INSURANCE
# ======================
car_insurance:
  - geico

health_insurance:
  - united healthcare
  - unitedhealth

renters_insurance:
  - lemonade insurance

# ======================
# INTERNET
# ======================
internet:
  - comcast
  - xfinity

# ======================
# DEBT
# ======================
debt:
  - discover
  - nelnet
  - student loan


# ======================
# MISCELLANOUs
# ======================
miscellaneous:
  - paypal

# ======================
# DO NOT AUTO-CATEGORIZE
# (intentionally omitted)
# ======================