# ======================
# INCOME
# ======================
income:
  - deposit ach
  - paycheck
  - venmo
  - zelle
  - deposit home banking transfer
  - gift
  - rent from

# =======================
# GIVING
# ======================
giving_church:
  - saint edward
  - diocesen
  - st mary's bookstore
  - church

giving_charity:
  - lifeline child

# ======================
# HOUSING
# ======================
housing_rent:
  - bh life rent

housing_utilities:
  - bh life rent

housing_pet:
  - pet rent

# ======================
# TRANSPORTATION
# ======================
transportation_gas:
  - auto care
  - gas
  - shell
  - exxon
  - chevron

transportation_airfare:
  - united airlines
  - spirit

# ======================
# FOOD
# ======================
food_groceries:
  - kroger
  - costco
  - publix
  - shoprite

food_dining:
  - popeyes
  - chipotle
  - moe's
  - chopt
  - diner
  - pizza
  - thai
  - no ches
  - grill

coffee:
  - starbucks
  - dunkin
  - caliber coffee
  - the well coffeehouse
  - the well
  - panera

# ======================
# PERSONAL / LIFESTYLE
# ======================
personal_fun:
  - mckay used books

health_hygiene:
  - walgreens
  - cvs

pets:
  - petco
  - petsmart
  - vetsource

education:
  - amazon books
  - audible
  - wgu
  - boot.dev
  - comptia
  - tryhackme
  - udemy
  - hackthebox
  - violin shop
  - myperfectresume

entertainment:
  - amc theatres

subscriptions:
  - netflix
  - spotify
  - hulu
  - disney+
  - crunchydrive
  - amazon prime
  - notion
  - prime video

business_expenses:
  - cloudflare
  - tnsos business

# ======================
# INSURANCE
# ======================
insurance_auto:
  - geico

insurance_health:
  - united healthcare

insurance_renters:
  - lemonade insurance

# ======================
# INTERNET
# ======================
internet:
  - comcast
  - xfinity

# ======================
# DO NOT AUTO-CATEGORIZE
# (intentionally omitted)
# ======================